### ISSUE TITLE
Раздел настроек "Специальные возможности" открывается криво с точки зрения UI

### ISSUE THREAD

**Issue by Minsky2x** [Computershik73/ViKaTouch#38]
Раздел настроек "Специальные возможности" открывается криво - отображаются лишь последние два пункта, хотя на экране достаточно места для отображения всех пунктов.
Курсор при этом находится на элементе, который находится где-то за пределами экрана.
Путём перемещения курсора можно отобразить и невидимые два пункта.
Устройство: Nokia E72.
![2z](https://user-images.githubusercontent.com/99919131/154612519-a11b6c67-3185-41a4-9657-ad4dfa0d7ed8.jpg)
Так же, при перемещении курсора на опцию "settings.showpics" - пропадает верхний пункт "Назад", хотя места на экране - достаточно.
![Scr000175](https://user-images.githubusercontent.com/99919131/154612713-773fbbd6-2e8d-42d2-ba23-f3a40f8142d7.jpg)

**Comment by Feodor0090** [comment]
Рискну предположить, что на всех экранах считается одинаковая высота контента, так что в подменю прокрутка ведет себя будто там есть невидимые элементы

**Comment by Minsky2x** [comment]
Да, поправлено, спасибо.
Правда, второе примечание - не поправлено:
При перемещении курсора на опцию "settings.showpics" - пропадает верхний пункт "Назад", хотя места на экране - достаточно.

![Scr000219](https://user-images.githubusercontent.com/99919131/155760479-928f1b49-856a-4239-91e7-ea5481a46381.jpg)

Но это, наверное, уже мелочи.
