### ISSUE TITLE
Предложение: выбор цвета курсора: добавить визуализации

### ISSUE THREAD

**Issue by Minsky2x** [Computershik73/ViKaTouch#69]
Выбор цвета курсора сейчас осуществляется выбором строчки в настройках с предопределёнными цветами.
Но хорошо бы добавить наглядности: например, возле каждой строчки нарисовать квадратик соответствующего цвета, так как не всегда по цифрам понятно, какой это цвет.

Как есть сейчас:

![Scr000187](https://user-images.githubusercontent.com/99919131/155035116-deabfcdb-df22-4c93-993f-226053043776.jpg)

Предлагаю что-то типа такого:

![primer](https://user-images.githubusercontent.com/99919131/155035121-4aafb74b-79fd-4975-8fa4-bb788a4290cd.jpg)

**Comment by Computershik73** [comment]
Настройки не предусматривают такой функционал

**Comment by Minsky2x** [comment]
Понял.
